### ISSUE TITLE
Update Better Sqlite3 v11.6.0

### ISSUE THREAD

**Issue by cyhnkckali** [m4heshd/better-sqlite3-multiple-ciphers#109]
Can you please upgrade to the current version? Will you continue to pursue this project?

**Comment by m4heshd** [comment]
I'm trying my best to push the updates today. SQLite is already up to date. Life is throwing some curveballs at the moment, and it's a bit difficult to find both motivation and time. Sorry about the delay.

**Comment by cyhnkckali** [comment]
Thank you for your effort

**Comment by m4heshd** [comment]
Closing the issue as the update was released moments ago.
