### ISSUE TITLE
Open a password protected better-sqlite3-multiple-ciphers database

### ISSUE THREAD

**Issue by leean613** [m4heshd/better-sqlite3-multiple-ciphers#14]
How can i open the encript database, with gui interface

**Comment by m4heshd** [comment]
Hello @leean613,

It depends on the GUI you're using. Something like [DB4S](https://github.com/sqlitebrowser/sqlitebrowser)?

**Comment by leean613** [comment]
![image](https://user-images.githubusercontent.com/66239916/159011372-d3980732-0a81-42e1-aa90-4712e98a3a4b.png)
the default encrypt type of better-sqlite3-multiple-ciphers is not sqlCipher, so i don't know what is the right way to fill this form (i suppose custom option, but how about the algorithm)

**Comment by jove0610** [comment]
I have the same problem and I'm also using DB Browser for GUI. Even if I specify sqlcipher on pragma like so:

```
db.pragma("cipher='sqlcipher'");
db.pragma("key='123'");
```

 I still can't open it if I click SQLCipher 3 and SQLCipher 4 options on the DB Browser.. There's no error message. It just closes the window then reopens it again.

**Comment by m4heshd** [comment]
As mentioned in [issue #5](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/issues/5#issuecomment-1008330548), DB Browser for SQLite reads and creates DBs that has an encrypted header which is called the `legacy` mode in this extension. You have to create the DB using following pragma to be able to open it in DB4S.

```js
const db = require('better-sqlite3-multiple-ciphers')(databasePath, { verbose: console.log });
db.pragma(`cipher='sqlcipher'`);
db.pragma(`legacy=4`);
db.pragma(`key='123'`);
```

**Comment by julianpoemp** [comment]
For anyone looking for a way to open the excrypted SQLite database with DBeaver: You can create a configuration as described here:
https://gist.github.com/thecodingcod/a3987ddde8892d1a6bda8bd94febb7d0

I got it working with sqlite-jdbc-3.46.0.0.jar .

**Comment by Jaarson** [comment]
Thanks @julianpoemp, for the link. I struggled to make it work in DBeaver but finally figured it out. It turns out the default cipher is `chacha20`, not `sqlcipher`, so this guide is not quite up to date. I added a relevant comment there, too.

**Comment by andrewschreiber** [comment]
Just use https://github.com/pawelsalawa/sqlitestudio instead of DB Browser for SQLite. Recommended in the readme.
