### ISSUE TITLE
db.register > TypeError: db.register is not a function

### ISSUE THREAD

**Issue by leopucci** [m4heshd/better-sqlite3-multiple-ciphers#16]
I was trying to set a hook like sqlite3_update_hook and found this way of doing using db.register and triggers
```
db.register({ varargs: true }, function logger(...values) {
  console.log(`row updated to (${values.join(', ')})`);
});

db.prepare('CREATE TRIGGER updateHook AFTER UPDATE ON data BEGIN SELECT logger(NEW.a, NEW.b, NEW.c); END').run();
```
But i was unable to use.  `TypeError: db.register is not a function`
Any hints on how update hooks can be created? 

https://github.com/JoshuaWise/better-sqlite3/issues/62#issuecomment-325797335

**Comment by m4heshd** [comment]
Hi @leopucci,

`db.register()` is not a valid function anymore. You're looking for [`db.function()`](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/blob/master/docs/api.md#functionname-options-function---this). Always doublecheck with the API documentation.

**Comment by leopucci** [comment]
Thank you man, you are the best. I saw the function in the documentation but wasn´t sure if it was the same. 
It works

  ```
db.function('logger', { varargs: true }, function logger(...values) {
    console.log(`TESTE row updated to (${values.join(', ')})`);
  });

  db.prepare('DROP TRIGGER IF EXISTS updateHook;').run();
  db.prepare(
    'CREATE TRIGGER updateHook AFTER UPDATE ON files BEGIN SELECT logger(NEW.a,NEW.b); END'
  ).run();
```
