### ISSUE TITLE
HI! I think your package rocks and many people will use it!

### ISSUE THREAD

**Issue by leopucci** [m4heshd/better-sqlite3-multiple-ciphers#3]
Hey there, didn´t know how to contact you guys so i am opening a welcome issue. 

Nice jobs from you guys building to all those architetures.
I will use this package and i think many people will do. 
Thanks for creating this.
:)

**Comment by m4heshd** [comment]
Hello @leopucci,

Glad it hear that it's becoming quite useful and thank you for giving this a try. More users always mean more stability for the library.

> Nice jobs from you guys building to all those architectures.

It indeed took an immense amount of testing but I'm glad it succeeded. I'm also planning on adding prebuild support for NW.js on all platforms. But I'm gonna be needing some input from a NW.js daily driver dev.

> Thanks for creating this.

The pleasure is mine. 😊

**Comment by leopucci** [comment]
@m4heshd, do you know some odm/orm that I could use with this lib?

**Comment by m4heshd** [comment]
I'm not sure if there is. But `typeorm` seem to support `better-sqlite3`. [`sequelize`](https://github.com/sequelize/sequelize/issues/11400) is also planning on adding support for `better-sqlite3` but that still wouldn't help if they won't allow to use a custom implementation of the library. That's something we have to spend a little time on to look into.

**Comment by m4heshd** [comment]
**UPDATE:**
Keep track of this issue at `typeorm`. https://github.com/typeorm/typeorm/issues/8475.
