### ISSUE TITLE
How to convert a non encrypted database to a encrypted database ?

### ISSUE THREAD

**Issue by Jun90925** [m4heshd/better-sqlite3-multiple-ciphers#30]
I have a app with better-sqlite3 database already, but how to convert it become a encrypted database ?

**Comment by m4heshd** [comment]
It's pretty simple as mentioned [in the documentation](https://github.com/m4heshd/better-sqlite3-multiple-ciphers#encryption). Although while proceeding to do so, I'd highly recommend using a database created with the same version of SQLite3 to avoid any unintended side effects.
