### ISSUE TITLE
How can I recover a corrupted encrypted db file

### ISSUE THREAD

**Issue by Jun90925** [m4heshd/better-sqlite3-multiple-ciphers#33]
Normally we can recover a corrupted database file by using
`sqlite3 crrupted.d .recover | sqlite3 fixed.db`

But how to recover a database if it is encrypted ？

**Comment by m4heshd** [comment]
This issue should be redirected to [SQLite3MultipleCiphers](https://github.com/utelle/SQLite3MultipleCiphers). Please leave a comment in this thread with that issue tagged. Closing for now.
