### ISSUE TITLE
Declaration file for module in Strict Mode

### ISSUE THREAD

**Issue by dlh2** [m4heshd/better-sqlite3-multiple-ciphers#39]
Looking at #22 

import Database from 'better-sqlite3-multiple-ciphers'

```
{
  "compilerOptions": {
    "target": "ES6",
    "module": "es2022",
    "moduleResolution": "NodeNext", // Node for ES6, Classic for Commonjs
    "lib": [
      "es2019",
      "dom"
    ],
    "strict": true,
  }
}

```

Shows the error:

Could not find a declaration file for module 'better-sqlite3-multiple-ciphers' node_modules/better-sqlite3-multiple-ciphers/lib/index.js' implicitly has an 'any' type

But if strict is `false`, it does work.

**Comment by m4heshd** [comment]
Hi, Can you check if you have the same issue with `better-sqlite3`?

**Comment by m4heshd** [comment]
Closing this issue since there isn't any activity. Feel free to reopen if there's any update.
