### ISSUE TITLE
How change encryption method?

### ISSUE THREAD

**Issue by yolopunk** [m4heshd/better-sqlite3-multiple-ciphers#4]
Encryption using default method sqleet. I want to know how change encryption method using sqlcipher.

But I want to switch sqlcipher. Due I am using typeorm. And I tried compile sqlcipher for better-sqlite3 but I failed.

Typeorm has an option named `key` for sqlcipher.

**Comment by m4heshd** [comment]
You can use a `PRAGMA` statement.

```js
const db = require('better-sqlite3-multiple-ciphers')('foobar.db', options);
db.pragma("PRAGMA cipher='sqlcipher'");
```

**Comment by yolopunk** [comment]
* The following method is in effect （using `better-sqlite3-multiple-ciphers`)

```js
// encrypt db
const db = require('better-sqlite3-multiple-ciphers')('foobar.db', { verbose: console.log })
db.pragma("cipher='sqlcipher'")
db.pragma(`rekey='secret-key'`)
db.prepare(`CREATE TABLE "post" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "text" varchar NOT NULL)`).run()
const stmt = db.prepare('INSERT INTO post (title, text) VALUES (?, ?)')
const info = stmt.run('Joey', 'my homie')
db.close()

// decrypt db
const db = require('better-sqlite3-multiple-ciphers')('foobar.db', { verbose: console.log });

db.pragma(`cipher='sqlcipher'`)
db.pragma("key='secret-key'");
const stmt = db.prepare("SELECT * FROM post")
console.log(stmt.get()); // { id: 1, title: 'Joey', text: 'my homie' }
```
* The following method is not valid （using `typeorm`)

```typescript
import { createConnection } from 'typeorm'
import { BetterSqlite3ConnectionOptions } from 'typeorm/driver/better-sqlite3/BetterSqlite3ConnectionOptions'
import { Post } from './entity/post'

const config: BetterSqlite3ConnectionOptions = {
  type: 'better-sqlite3',
  key: 'secret-key',
  database: 'foobar.db',
  driver: require('better-sqlite3-multiple-ciphers'),
  entities: ['entity/*.ts'],
  logging: true,
  verbose: console.log,
  prepareDatabase: db => {
    db.pragma(`cipher='sqlcipher'`)
  }
}

const start = async () => {
  const conn = await createConnection(config)
  const posts = await conn.manager.find(Post)
  console.log(posts)
}

start()  // SqliteError: file is not a database
```

I don’t know what’s wrong with my options for `typeorm`

**Comment by m4heshd** [comment]
Instead of using the `key` field, can you try the following?

```ts
prepareDatabase: db => {
    db.pragma(`cipher='sqlcipher'`)
    db.pragma(`key='secret-key'`)
}
```

**Comment by yolopunk** [comment]
I tried.  The same mistake！ @m4heshd

**Comment by m4heshd** [comment]
Hmm that's unfortunate. I think it would be beneficial to move this question to [`typeorm`](https://github.com/typeorm/typeorm/issues) issue tracker. People with more experience related to `typeorm` would be able to diagnose this much quicker. Unfortunately I lack the time to go through `typeorm`'s internals at this moment. Make sure to post the complete findings including the above code. Also make sure to tag this issue in your new issue so I can assist there too.

**Comment by m4heshd** [comment]
One more thing. It would really help if you can create a reproducible repo of this test project with the above code so maybe we can take a look at that.

**Comment by yolopunk** [comment]
Below is the reproducible repo link

https://github.com/yolopunk/typeorm-better-sqlite-sqlcipher

**Comment by m4heshd** [comment]
This issue is confirmed to be third-party and being tracked at https://github.com/typeorm/typeorm/issues/8475.

**Comment by yolopunk** [comment]
Now that found the problem.I'll turn this issue off. Thank you again
