### ISSUE TITLE
Can you include a type definition file for the TypeScript language?

### ISSUE THREAD

**Issue by ryusei-48** [m4heshd/better-sqlite3-multiple-ciphers#44]
I am currently developing a desktop app in Electron.
I am also finding it troublesome to set up VS Code and compile without errors.
Thank you, I will try to find a way to make it work.

**Comment by m4heshd** [comment]
Hi @ryusei-48,

I'm not a TypeScript user but I assumed that #32 already fixed this. Is that not the case? 🤔

**Comment by m4heshd** [comment]
> The type definition file for "better-sqlitet" was published here

That, I'm aware of and in fact, `@types/better-sqlite3` should've been sufficient since it's specified in the metadata. I've even tested this. Everything was picked up properly. It's quite odd it has suddenly become an issue.

> As a matter of fact, since the API is the same for both, there was no problem in using them interchangeably.

That's not entirely true since some different, exclusive functionality has been added to bs3mc recently. Either way, I'll take a look at it as soon as I've got some time on my hands.

**Comment by ryusei-48** [comment]
I see you were on vacation. Thank you for your reply. Currently, it is working perfectly in the main thread of Electron. However, only the heavy processing is flowing to threads, so there is a possibility of locking up when manipulating the database in the main thread. I will consider whether to move all database processing to threads.

**Comment by joyexpr** [comment]
any progress ?

**Comment by m4heshd** [comment]
@ryusei-48, @joyexpr Can you try the [`dev` branch](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/tree/dev) and see if the type definitions work?

**Comment by Kloen** [comment]
It does work for me so far:
![image](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/9112818/62329f51-a83c-4856-a4df-0e74cea08991)

**Comment by m4heshd** [comment]
@Kloen That would do it. Thanks.

The feature is now merged and available in `v8.5.1-beta.0`.

**Comment by Kloen** [comment]
@m4heshd worth mention that after switching to `v8.5.1-beta.0`
![image](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/9112818/cfbca0ec-e9e6-44fa-9220-b0f228939384)

While using the dev branch:
![image](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/9112818/6ac09485-9aa0-4d42-8ab8-bbe4d0178d30)

**Comment by m4heshd** [comment]
@Kloen Thank you for reporting. I forgot to include the definitions file in the published package on NPM. 🤦🏽

![image](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/6711514/81188b2c-d909-4571-b55d-570715589c4a)

**Comment by m4heshd** [comment]
@Kloen Can you test `v8.5.1-beta.1`?

**Comment by Kloen** [comment]
@m4heshd looks like it did the trick now:
![image](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/9112818/51840e80-65ec-4ea0-9b42-7e318b362583)
