### ISSUE TITLE
Support Electron v25

### ISSUE THREAD

**Issue by willemdjong** [m4heshd/better-sqlite3-multiple-ciphers#52]
Hello,

I'm reaching out to request support for Electron v25. I'm experiencing a crash with the following error message: "Error: Could not detect abi for version 25.2.0 and runtime electron. Updating 'node-abi' might help solve this issue if it is a new release of Electron."

Thank you in advance for your assistance.

Best regards,

**Comment by m4heshd** [comment]
Hi,

I've already added the support in https://github.com/m4heshd/better-sqlite3-multiple-ciphers/commit/3c76237c19ec8e5d3e2549ff78b4f7ead9d72402 but never did a release for just that. It's gonna need a new beta release for the package. 

Subscribe to release notifications. I'll try to do a beta as soon as I get some free time.

**Comment by m4heshd** [comment]
UPDATE:

It seems like I can do a stable release `8.5.0` since @mceachen also did because of all the nagging at https://github.com/WiseLibs/better-sqlite3/pull/1013. 😆

**Comment by m4heshd** [comment]
Just released `v8.5.0`. Prebuilt binaries will be ready in a [couple of hours](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/5601926324). Closing the issue.

**Comment by willemdjong** [comment]
Referring back to your previous fix, it appears that there might be a missing prebuilt binary package for Windows. Here's the relevant log:

`npm run build:main exited with code 0
  • electron-builder  version=24.6.3 os=22.2.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=release/build/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=better-sqlite3-multiple-ciphers@8.5.0 platform=win32 arch=arm64
  • install prebuilt binary  name=better-sqlite3-multiple-ciphers version=8.5.0 platform=win32 arch=arm64 napi=
  ⨯ cannot build native dependency  reason=prebuild-install failed with error and build from sources not possible because platform or arch not compatible
                                    cause=exit status 1
                                    errorOut=prebuild-install info begin Prebuild-install version 7.1.1
    prebuild-install warn install prebuilt binaries enforced with --force!
    prebuild-install warn install prebuilt binaries may be out of date!
    prebuild-install info looking for local prebuild @ prebuilds/better-sqlite3-multiple-ciphers-v8.5.0-electron-v116-win32-arm64.tar.gz
    prebuild-install info looking for cached prebuild @ /Users/user/.npm/_prebuilds/095f9e-better-sqlite3-multiple-ciphers-v8.5.0-electron-v116-win32-arm64.tar.gz
    prebuild-install http request GET https://github.com/m4heshd/better-sqlite3-multiple-ciphers/releases/download/v8.5.0/better-sqlite3-multiple-ciphers-v8.5.0-electron-v116-win32-arm64.tar.gz
    prebuild-install http 404 https://github.com/m4heshd/better-sqlite3-multiple-ciphers/releases/download/v8.5.0/better-sqlite3-multiple-ciphers-v8.5.0-electron-v116-win32-arm64.tar.gz
    prebuild-install warn install No prebuilt binaries found (target=25.0.1 runtime=electron arch=arm64 libc= platform=win32)
    
                                    command=/Users/user/.nvm/versions/node/v16.16.0/bin/node /Users/user/code/electron-react-boilerplate/release/app/node_modules/prebuild-install/bin.js --platform=win32 --arch=arm64 --target=25.0.1 --runtime=electron --verbose --force
`

**Comment by m4heshd** [comment]
@willemdjong That's expected because we aren't building for Windows on `arm` since it's not possible to do so at the moment. GitHub doesn't provide `arm` based runners. You can take a look at their response at https://github.com/actions/runner-images/issues/768. `arm64` is only supported using self-hosted runners which aren't free to set up.
