### ISSUE TITLE
Installation error in Termux!!

### ISSUE THREAD

**Issue by Vanillma** [m4heshd/better-sqlite3-multiple-ciphers#53]
Hey Bro
I encounter this error when installing in Termux!!
![Screenshot_20230720-213108](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/95992420/d911c361-5bb7-4c3c-9890-8915411be8d5)
![Screenshot_20230720-213114](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/95992420/d5cdd0ef-c9a6-46ba-a2bd-aa32c7cf0ca7)

Meanwhile, I have successfully installed the following packages:
![Screenshot_20230720-213012](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/95992420/4799f560-b931-4522-92a9-23af3492c801)

clang complains about flag (-march=native).

**Comment by Vanillma** [comment]
> Sorry that it took a long time for me to respond.
> 
> First, can I know more about your device? What arch is its CPU? Any chance it's emulated? (x86). Pre-built binaries are available for both `armv7` and `arm64`. So it's odd that your installation didn't download them automatically. Can you also check what [`os.platform()`](https://nodejs.org/api/os.html#osplatform) returns on your device? There's a chance it might return `android`, which would be a problem.
> 
> Second, this made me revisit the build configuration and realized that the `-march=native` flag isn't necessary. The problem is, I can't remember why exactly I added this flag. I only have a faint memory of `arm` builds failing to compile without it. I just removed the flag in [4d6416e](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/commit/4d6416efd0267715db46f4432f496fbdf2795fff), and you can check if it works now. I'm still skeptical about using Clang though. If you can, use GCC.

hey bro
Sorry for the delay...I was testing and learning more about this.

First, about the type of platform...you true guessed it, android is returned.
![Screenshot_20230728-051906](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/95992420/6dbe75c1-7daf-4a6c-bcc0-36ab1c7c354a)

Second, general information about my system:
```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=12145
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://mirror.bardia.tech/termux/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
7.1.2
Kernel build information:
Linux localhost 3.4.0-Lineage #1 SMP PREEMPT Wed May 2 23:03:33 IST 2018 armv7l Android
Device manufacturer:
samsung
Device model:
SM-G7102
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api
```
And finally, the results of the solutions I tried.

I tried to install version 8.5 from npm but still got the same weird error
![Screenshot_20230728-053613](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/95992420/27592f8b-b0cf-4c92-bb23-8064b3555266)


Then I decided to clone the GitHub files
And then I tried the npm build command without any error, the build and release folder was created.
![Screenshot_20230728-053941](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/95992420/07da93bc-1a31-41e9-8825-d65d41cd9020)

(I don't know exactly what these folders are for...but it seems to be created for uploading in the npm system...can't it be made into a local package??)

After some more research I found out that it can be tested with the npm link command...I linked it to my project and now it works fine!
![Screenshot_20230728-054159](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/95992420/9ece45ef-26ac-4f63-8896-3498626ead88)
![Screenshot_20230728-055242](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/95992420/cb26c41f-3820-4fd0-a17e-c289a139ac34)
![Screenshot_20230728-055304](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/95992420/519a9a83-1cdc-41f8-8102-526500f2d1cd)


(Another note, I encountered this error when I was trying to use prebuild arm...then I found [this explanation.](https://github.com/termux/termux-packages/issues/121))
![Screenshot_20230728-064216](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/95992420/ceab9617-e538-4608-b777-3e5073e976c1)

**Comment by m4heshd** [comment]
> I tried to install version 8.5 from npm but still got the same weird error

It wouldn't work because it's still the same build. You'd be able to install the next beta or stable release properly.

> After some more research I found out that it can be tested with the npm link command...I linked it to my project and now it works fine!

You don't have to do all that. You can directly install the package with the latest updates using a link to the repo.

```yml
npm install https://github.com/m4heshd/better-sqlite3-multiple-ciphers/tarball/master
```

This will install the package like a regular npm package.

**Comment by Vanillma** [comment]
> > I tried to install version 8.5 from npm but still got the same weird error
> 
> It wouldn't work because it's still the same build. You'd be able to install the next beta or stable release properly.
> 
> > After some more research I found out that it can be tested with the npm link command...I linked it to my project and now it works fine!
> 
> You don't have to do all that. You can directly install the package with the latest updates using a link to the repo.
> 
> ```yaml
> npm install https://github.com/m4heshd/better-sqlite3-multiple-ciphers/tarball/master
> ```
> 
> This will install the package like a regular npm package.

Yes...you are right...now it installed without any error.
Oh, it was a disturbing flag...😄
![Screenshot_20230728-212429](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/95992420/30757de8-6fdb-4f56-b6ba-30b980282880)
