### ISSUE TITLE
Support Electron 26

### ISSUE THREAD

**Issue by willemdjong** [m4heshd/better-sqlite3-multiple-ciphers#57]
The version 8.5.2 has not been released on npm for [better-sqlite3-multiple-ciphers](https://www.npmjs.com/package/better-sqlite3-multiple-ciphers).

**Comment by m4heshd** [comment]
Big mistake on my part. Both `v8.5.2` and `v8.6.0` are released now. Thanks for bringing this to my attention.

**Comment by willemdjong** [comment]
My app is crashing as soon as I use better-sqlite3-multiple-ciphers in code. ~ No error log, app just crashes ~
