### ISSUE TITLE
How do you suggest rekeying with WAL?

### ISSUE THREAD

**Issue by coltoneshaw** [m4heshd/better-sqlite3-multiple-ciphers#64]
Right now I have `journal_mode = WAL` set. You cannot run a `rekey` when this is set. Would you suggest doing `journal_mode = delete`, rekey, then enabling `wal` ?

**Comment by m4heshd** [comment]
I'm not sure if just running a checkpoint would help with this. That's all that came to my mind at the moment. Unfortunately, I'm away at the moment. Can't test anything. Also for the sake of having better knowledge on this, I'd feel much better if @utelle answered this.

**Comment by utelle** [comment]
> Right now I have `journal_mode = WAL` set. You cannot run a `rekey` when this is set. Would you suggest doing `journal_mode = delete`, rekey, then enabling `wal` ?

_Short answer_: **Yes**.

_Long answer_: The current implementation of the rekeying operation in the underlying _SQLite3 Multiple Ciphers_ library tries to rekey a database **in-place** if possible, thus keeping the disk storage requirements to a minimum. However, this does not work if WAL journaling is used and could easily lead to database corruption. In principle, rekeying via a vacuum operation could possibly work in WAL mode, if certain restrictions are not violated. However, to be on the safe side _SQLite3 Multiple Ciphers_ currently does not support rekeying in WAL mode and issues an error message. That is, to rekey an encrypted database you need to switch temporarily to journal mode DELETE.

**Comment by coltoneshaw** [comment]
> _Long answer_: The current implementation of the rekeying operation in the underlying _SQLite3 Multiple Ciphers_ library tries to rekey a database **in-place** if possible, thus keeping the disk storage requirements to a minimum. However, this does not work if WAL journaling is used and could easily lead to database corruption. In principle, rekeying via a vacuum operation could possibly work in WAL mode, if certain restrictions are not violated. However, to be on the safe side _SQLite3 Multiple Ciphers_ currently does not support rekeying in WAL mode and issues an error message. That is, to rekey an encrypted database you need to switch temporarily to journal mode DELETE.


This is perfect! Thank you! The journal switch operation seems to be fairly fast as well, so no big issues there. What would it look like to do it via a vacuum?

**Comment by utelle** [comment]
> What would it look like to do it via a vacuum?

1. Independent of whether the database is encrypted or not, vacuuming a database in WAL mode requires free disk space of about **twice** the database size. In DELETE mode only about **once** the database size is required.
2. As said _SQLite3 Multiple Ciphers_ does currently not support rekeying in WAL mode. You could use `VACUUM INTO` to create a copy of the original database with a different key, but that's not the same as rekeying the original database.
3. Maybe it is possible to change the implementation of the rekey operation in _SQLite3 Multiple Ciphers_, so that it uses `VACUUM` in WAL mode. However, there are additional restrictions: the cipher scheme must be the same as that of the original database and the page size must not be changed.

**Comment by m4heshd** [comment]
Thank you @utelle. Closing this as solved.

**Comment by m4heshd** [comment]
> It looks like I was missing a `db.prepare('VACUUM').run();`

This is always advised if you're doing a journal mode change.

> renaming the db file without also realizing that the `-whm` and `-shm` files were still there

If you're properly closing all connections (which should trigger checkpoints), these journal files should go away. I have dedicated logic on all of my applications to check for those files before messing with the database files on storage.
