### ISSUE TITLE
is not a valid Win32 application

### ISSUE THREAD

**Issue by narianangel** [m4heshd/better-sqlite3-multiple-ciphers#65]
Hi!

I was working all day with this without issues... but now, when I try to launch my app I get the next error:

`electron\\node_modules\\better-sqlite3-multiple-ciphers\\build\\Release\\better_sqlite3.node is not a valid Win32 application.`

What is happening now?

Thanks!

**Comment by m4heshd** [comment]
Can you link a reproducible repo so I can take a look at what might be causing the issue?

Also, make sure to mention your Windows version and the Node version you're using locally.

**Comment by narianangel** [comment]
Repo its private for my company...

**Windows:** 
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045

**Node**
v16.15.0

**Comment by m4heshd** [comment]
> Repo its private for my company...

Unfortunately, there's no other way for me to debug your specific scenario without a way to reproduce it. I don't want you to make your private code public. Instead, you have to recreate the issue on a new repo in a minimal way. Retrace your steps up to the point where you ran into this issue, clean that code up to the minimal requirements, and link that repo here.

**Comment by narianangel** [comment]
I deleted node_modules from Angular project and Electron folder and run `npm install` again in both, and it seems that everything is going well for now.

**Comment by m4heshd** [comment]
Glad to know the issue was solved. Closing this issue. Feel free to reopen if the issue resurfaces.
