### ISSUE TITLE
Alternative database viewer for default encryption?

### ISSUE THREAD

**Issue by titanism** [m4heshd/better-sqlite3-multiple-ciphers#68]
Curious if you knew of a different DB viewer or what you use instead of <https://github.com/sqlitebrowser/sqlitebrowser> with the defaults in this project?

**Comment by m4heshd** [comment]
You can use [SQLiteStudio](https://github.com/pawelsalawa/sqlitestudio). It uses [SQLite3MultipleCiphers](https://github.com/utelle/SQLite3MultipleCiphers) as the default DB lib.

**Comment by m4heshd** [comment]
You're welcome to create a PR with those documentation improvements.
