### ISSUE TITLE
Add support in knex library for `better-sqlite3-multiple-ciphers`

### ISSUE THREAD

**Issue by titanism** [m4heshd/better-sqlite3-multiple-ciphers#69]
Right now `better-sqlite3` is supported by [knex](https://github.com/knex/knex) &ndash; is there a way to workaround this string comparison (or make a resolution someone to make it work)?  A link to the commit we'd have to mirror with `better-sqlite3-multiple-ciphers` instead of `better-sqlite3` as the string is below.

Ref:
- <https://github.com/knex/knex/commit/2bd181171b53dfa967503e53c90fb8201b46980e>
- <https://github.com/knex/knex/issues/4511>

**Comment by m4heshd** [comment]
It would be THEIR responsibility to add this functionality if the users of their library require it. Therefore, I'm closing this issue as it is now being tracked in the appropriate place. I suggest you create a PR there so it makes the job easier for the devs and as a plus, you'll get much better attention to the functionality you specifically require.
