### ISSUE TITLE
9.4.1 breaks with electron@29.0.1 (latest Stable)

### ISSUE THREAD

**Issue by 6180339** [m4heshd/better-sqlite3-multiple-ciphers#86]
Works fine with electron@28.2.4
Both better-sqlite3 and multiple-ciphers break with electron LTS
Env: win64
Command: ` node-gyp rebuild --release --target=29.0.1  --dist-url=https://electronjs.org/headers`

**Comment by m4heshd** [comment]
@6180339 Already [tested here](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/7969186491) and being [tracked in the upstream](https://github.com/WiseLibs/better-sqlite3/pull/1147#issuecomment-1958408256).

**Comment by pelletier197** [comment]
Hello! Has there been any progress on this ? I tried upgrading to electron 29 and I faced an issue with better-sqlite as well. Thanks a lot!

**Comment by sparecycles** [comment]
@pelletier197 please see if https://github.com/WiseLibs/better-sqlite3/issues/1127 works for you.

**Comment by m4heshd** [comment]
Fixed in [`v9.4.5`](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/releases/tag/v9.4.5).
