### ISSUE TITLE
9.4.1 is not on NPM

### ISSUE THREAD

**Issue by n9lsjr** [m4heshd/better-sqlite3-multiple-ciphers#87]
The title says it. 9.4.0 is the latest version on npm.

Don't know if you have a reason. But maybe forgot?

**Comment by n9lsjr** [comment]
Ok I noticed you had some problems with the Electron -> win32 build and you are fixing it. Closing this.

**Comment by m4heshd** [comment]
I have no idea how I missed that. Just published. Thank you for letting me know. I'm probably going to be automating this task.

**Comment by n9lsjr** [comment]
Np mate. Thanks for a great package. It was really smooth to switch from a normal sqlite3 DB -> this.
