### ISSUE TITLE
Rekey operation does not throw an error and results in corrupt database file when in WAL mode

### ISSUE THREAD

**Issue by titanism** [m4heshd/better-sqlite3-multiple-ciphers#91]
Related to #64 - a rekey operation does not throw an error until you call vacuum, and when that occurs the database is stuck in a corrupt state.

Further attempts to open a database that "rekey" was invoked upon while in WAL mode fail, resulting in a corrupt database file that cannot be opened.

```sh
db.pragma('key="foo"');
db.pragma('rekey="baz"'); // <--- does not throw an error when already in WAL mode
```

**Comment by m4heshd** [comment]
I'm closing this as it's the intended behavior and advised to do so. I do feel like this should go in the SQLite3MC documentation. Feel free to open an issue about it in the [SQLite3MC](https://github.com/utelle/SQLite3MultipleCiphers) repo if you think so.
