### ISSUE TITLE
Electron 31 support

### ISSUE THREAD

**Issue by reintjanhoiting1** [m4heshd/better-sqlite3-multiple-ciphers#93]
How can we get support for electron 31? since 31 is stable?

Here is an example in a different repo:
https://github.com/WiseLibs/better-sqlite3/pull/1200

**Comment by m4heshd** [comment]
@reintjanhoiting1 It's already merged (5f4d5c99ef89ec32951164cdf79f06dbc09472ca) and being worked on. But there's a lot more going on with broken builds. You're going to have to compile the addon yourself for the moment.

**Comment by reintjanhoiting1** [comment]
@m4heshd , Thanks for the update!

**Comment by m4heshd** [comment]
@reintjanhoiting1 Just realized you were the one who just sent the big donation my way. Thank you for your support. It really motivates me to put more time and effort into this addon.

**Comment by reintjanhoiting1** [comment]
@m4heshd Thanks for your reaction and your support. I am glad you will put more time and effort into this add-on. You have more experience in this area than I do.

**Comment by m4heshd** [comment]
Hi, this has been fixed in the latest release. Closing the issue. Feel free to reopen or add to the conversation if there are any issues. 😊
