### ISSUE TITLE
Mac OS X64 builds missing from v11.0.0-beta.0 Pre-release

### ISSUE THREAD

**Issue by reintjanhoiting1** [m4heshd/better-sqlite3-multiple-ciphers#96]
Hi, @m4heshd 

This morning, we discovered that the new package better-sqlite-multiple-ciphers no longer includes prebuilt Mac OS x64 binaries. This issue arose because the GitHub Actions setup you are using employs macos-latest, which GitHub recently updated to an arm64 machine. As a result, the prebuilt binaries for x64 are not being generated.

**change by github:** 
"macos-latest" YAML label is now the same as using macos-14. (macOS 14 Arm64). They changed this 1 month ago, https://github.com/actions/runner-images/blob/main/README.md

**How to Fix?**
**Quick Fix:**
You can temporarily resolve this issue by using macos-13 or macos-14-large instead of macos-latest. The macOS-13 machine operates on an x64 architecture.

we did it in a fork over here:
https://github.com/AppMachine/better-sqlite3-multiple-ciphers/commit/ddea769d044e101ad475846560641c29175b823c

**Better Solution:**
For a more robust and future-proof solution, you can update your matrix and specify the architecture as follows:
yaml
Copy code
strategy:
  fail-fast: false
  matrix:
    os:
      - macos-11
    arch: [x64, arm64]
Additionally, ensure the build command is executed with the correct architecture:
yaml
Copy code
- if: matrix.os == 'macos-11' && matrix.arch == 'arm64'
  run: ${{ env.NODE_20_BUILD_CMD }} --arch arm64
This configuration ensures that the build is correctly targeted for the arm64 architecture when using an arm64 machine.
Please let me know if you have any questions or need further assistance with this setup.

**Comment by reintjanhoiting1** [comment]
upstream we see the same issue:
https://github.com/WiseLibs/better-sqlite3/releases/tag/v11.0.0

**Comment by m4heshd** [comment]
@reintjanhoiting1 Oh I was waiting for this day 😁. I can't believe I missed the missing prebuilt binaries on the release. We should've been using specific versions for each runner in the first place as there were discussions in the past.

Thank you for bringing this to my attention. I'll make sure to make this change on the upstream and bring that down to this fork as soon as it's live.
