### ISSUE TITLE
Async/await support with `iterate()`

### ISSUE THREAD

**Issue by titanism** [m4heshd/better-sqlite3-multiple-ciphers#97]
Curious as to the support of async/await, e.g. `await foo()` inside an `iterate()` call?

<https://github.com/m4heshd/better-sqlite3-multiple-ciphers/blob/master/docs/api.md#iteratebindparameters---iterator>

**Comment by m4heshd** [comment]
Did you check to see if it functions properly on the upstream? If not, this issue should be opened on the BS3 repo instead.

**Comment by m4heshd** [comment]
I see. Then I urge you to open an issue there _(I see that you already did)_ to get proper support for this. Glad you caught this. Closing the issue here.
